%%{init: {"flowchart": {"defaultRenderer": "elk"}}}%%
flowchart TD
A[/"用户输入内容"/]
B{"输入是否为空？"}
C[/"提示重新输入"/]
D[["调用处理模块"]]
E[/"输出结果"/]

A --> B
B -->|为空| C
C -.->|返回| A
B -->|不为空| D
D --> E
E -.->|返回| A