%%{init: {"flowchart": {"defaultRenderer": "elk"}}}%%
flowchart TD
A(["开始"])
B[/"用户上传文件"/]
C{"文件是否为空？"}
D[/"提示用户重新上传"/]
E{"文件格式是否支持？"}
F[/"提示用户重新上传"/]
G{"文件大小是否超过限制？"}
H[/"提示用户压缩文件后重新上传"/]
I[["调用文件解析模块"]]
J{"文件解析是否成功？"}
K[["调用错误记录模块"]]
L[/"输出解析结果并保存文件信息"/]

A --> B
B --> C
C -->|为空| D
D -.->|返回| B
C -->|不为空| E
E -->|不支持| F
F -.->|返回| B
E -->|支持| G
G -->|超过| H
H -.->|返回| B
G -->|未超过| I
I --> J
J -->|失败| K
K -.->|返回| B
J -->|成功| L