%%{init: {"flowchart": {"defaultRenderer": "elk"}}}%%
flowchart TD
A[/"用户输入账号和密码"/]
B{"登录信息是否完整？"}
C[/"提示用户重新输入"/]
D[["调用登录验证模块"]]
E{"账号密码是否正确？"}
F[/"提示用户重新登录"/]
G{"判断用户是否具有访问权限"}
H[/"显示无权限提示"/]
I[/"进入系统首页并加载用户菜单"/]

A --> B
B -->|不完整| C
B -->|完整| D
C -.->|返回| A
D --> E
E -->|错误| F
E -->|正确| G
F -.->|返回| A
G -->|无权限| H
G -->|有权限| I
H -.->|返回| A